/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import com.sun.org.apache.xpath.internal.operations.Plus;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucianoRex
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private DefaultTableModel model;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBProdutos = new javax.swing.JTable();
        jTCod = new javax.swing.JTextField();
        jTDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jTvalor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTQtde = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLtotal = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JToggleButton();

        jLabel3.setText("jLabel3");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTBProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor", "Quantidade", "Total"
            }
        ));
        jTBProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBProdutos);

        jLabel1.setText("Cód.");

        jLabel2.setText("Descrição");

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Plus-20.png"))); // NOI18N
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ok-20.png"))); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor");

        jLabel5.setText("Quantiddade");

        jLabel6.setText("Total");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel 2-20.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLtotal.setText("0");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delete-20.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit-20.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCod, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTvalor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(jTQtde, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 330, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLtotal)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLtotal))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    boolean editando = false;
    boolean inserir = false;

    private void verificaLinha() {
        if (jTBProdutos.getRowCount() > 0) {
        } else {
            btnOk.setEnabled(false);
        }
    }

    private void totalizador() {
        String total = "";
        String qtde = "";
        double tot = 0;
        int countLinha = jTBProdutos.getRowCount();
        for (int i = 0; i < countLinha; i++) {
            total = (String) jTBProdutos.getValueAt(i, 4);
            qtde = (String) jTBProdutos.getValueAt(i, 3);
            tot += Double.parseDouble(total);
        }
        System.out.println(countLinha);
        jLtotal.setText(Double.toString(tot));
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnCancelar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnOk.setEnabled(false);      
        
//        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Plus-20.png")));
//        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ok-20.png")));
//        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel 2-20.png")));
//        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delete-20.png")));
//        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit-20.png")));
        jTCod.setEnabled(false);
        jTDescricao.setEnabled(false);
        jTQtde.setEnabled(false);
        jTvalor.setEnabled(false);
        model = (DefaultTableModel) jTBProdutos.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_formWindowOpened

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
      
        inserir = true;
        btnCancelar.setEnabled(true);
        btnOk.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);

        jTCod.setText("");
        jTDescricao.setText("");
        jTvalor.setText("");
        jTQtde.setText("");

        jTCod.setEnabled(true);
        jTDescricao.setEnabled(true);
        jTQtde.setEnabled(true);
        jTvalor.setEnabled(true);
        inserir = false;
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        String cod = jTCod.getText();
        String descricao = jTDescricao.getText();
        String valor = jTvalor.getText();
        String qtde = jTQtde.getText();
        String total = Double.toString(Double.parseDouble(valor) * Double.parseDouble(qtde));

        String linha[] = {cod, descricao, valor, qtde, total};
        model.addRow(linha);
        jTCod.setText("");
        jTDescricao.setText("");
        jTvalor.setText("");
        jTQtde.setText("");
        jTCod.requestFocus();
        jTCod.setEnabled(false);
        jTDescricao.setEnabled(false);
        jTQtde.setEnabled(false);
        jTvalor.setEnabled(false);
        totalizador();
        inserir = false;
        btnCancelar.setEnabled(false);
        btnOk.setEnabled(false);
        if (jTBProdutos.getRowCount() > 0) {
            btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (editando) {
            btnExcluir.setEnabled(true);
            btnInserir.setEnabled(true);
            btnOk.setEnabled(true);
            jTCod.setEnabled(false);
            jTDescricao.setEnabled(false);
            jTQtde.setEnabled(false);
            jTvalor.setEnabled(false);
            int linha = jTBProdutos.getSelectedRow();
            String cod = (String) jTBProdutos.getValueAt(linha, 0);
            jTCod.setText(cod);
            String descricao = (String) jTBProdutos.getValueAt(linha, 1);
            jTDescricao.setText(descricao);
            String preco = (String) jTBProdutos.getValueAt(linha, 2);
            jTvalor.setText(preco);
            String qtde = (String) jTBProdutos.getValueAt(linha, 3);
            jTQtde.setText(qtde);
            btnEditar.doClick();
            btnCancelar.setEnabled(false);
            totalizador();
        } else {
            btnCancelar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnOk.setEnabled(false);
            jTCod.setText("");
            jTDescricao.setText("");
            jTvalor.setText("");
            jTQtde.setText("");
            jTCod.setEnabled(false);
            jTDescricao.setEnabled(false);
            jTQtde.setEnabled(false);
            jTvalor.setEnabled(false);
            inserir = false;
            totalizador();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTBProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBProdutosMouseClicked
        int linha = jTBProdutos.getSelectedRow();
        String cod = (String) jTBProdutos.getValueAt(linha, 0);
        jTCod.setText(cod);
        String descricao = (String) jTBProdutos.getValueAt(linha, 1);
        jTDescricao.setText(descricao);
        String preco = (String) jTBProdutos.getValueAt(linha, 2);
        jTvalor.setText(preco);
        String qtde = (String) jTBProdutos.getValueAt(linha, 3);
        jTQtde.setText(qtde);
    }//GEN-LAST:event_jTBProdutosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (btnEditar.isSelected()) {
            editando = true;
            btnCancelar.setEnabled(true);
            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ok-20.png")));
            btnExcluir.setEnabled(false);
            btnInserir.setEnabled(false);
            btnOk.setEnabled(false);
            jTCod.setEnabled(true);
            jTDescricao.setEnabled(true);
            jTQtde.setEnabled(true);
            jTvalor.setEnabled(true);

            totalizador();

        } else {
            editando = false;
            btnCancelar.setEnabled(false);
            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit-20.png")));
            btnExcluir.setEnabled(true);
            btnInserir.setEnabled(true);
            btnOk.setEnabled(false);

            totalizador();
            int i = jTBProdutos.getSelectedRow();
            model.setValueAt(jTCod.getText(), i, 0);
            model.setValueAt(jTDescricao.getText(), i, 1);
            model.setValueAt(jTQtde.getText(), i, 2);
            model.setValueAt(jTvalor.getText(), i, 3);
            jTCod.setEnabled(false);
            jTDescricao.setEnabled(false);
            jTQtde.setEnabled(false);
            jTvalor.setEnabled(false);

        }
        //
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (jTBProdutos.getRowCount() == 1) {
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
        model.removeRow(jTBProdutos.getSelectedRow());

    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLtotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBProdutos;
    private javax.swing.JTextField jTCod;
    private javax.swing.JTextField jTDescricao;
    private javax.swing.JTextField jTQtde;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTvalor;
    // End of variables declaration//GEN-END:variables
}
